use_frameworks!

target 'CGExtensions_Example_iOS' do
  pod 'CGExtensions', :path => '../'

  target 'CGExtensions_Tests_iOS' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
